s2e_magasin_spring/src/com/greta/s2e/magasin/beans/Article.java
package com.greta.s2e.magasin.beans;

import static com.greta.s2e.magasin.globals.Constants.*;

import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Classe entity Article
 */
@Entity
@Table(name = TABLE_ARTICLE)
public class Article {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = TABLE_ARTICLE_ID)
	protected int id;
	@Column(name = TABLE_ARTICLE_LIBELLE)
	protected String libelle;
	@Column(name = TABLE_ARTICLE_MARQUE)
	protected String marque;
	@Column(name = TABLE_ARTICLE_MODELE)
	protected String modele;
	@Column(name = TABLE_ARTICLE_EQUIVALENCE)
	protected int equivalence;
	@Column(name = TABLE_ARTICLE_PRIXESTIME)
	protected float prix;
	@Column(name = TABLE_ARTICLE_QUANTITETOTALE)
	protected double quantiteTotale;
	@OneToOne (mappedBy = "article")
	protected Stock stock;
	@OneToMany(mappedBy = "article") 	
	List<Demande> demandes = new ArrayList<>();
	@OneToMany(mappedBy = "article") 	
	List<Catalogue> catalogues = new ArrayList<>();
	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLibelle() {
		return libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getMarque() {
		return marque;
	}

	public void setMarque(String marque) {
		this.marque = marque;
	}

	public String getModele() {
		return modele;
	}

	public void setModele(String modele) {
		this.modele = modele;
	}

	public int getEquivalence() {
		return equivalence;
	}

	public void setEquivalence(int equivalence) {
		this.equivalence = equivalence;
	}

	public float getPrix() {
		return prix;
	}

	public void setPrix(float prix) {
		this.prix = prix;
	}
	
	public void majPrix(float nouveauPrix, double nouvelleQuantite) {
		float quantiteTotale = (float) this.quantiteTotale;
		float newQuantite = (float) nouvelleQuantite;
		this.prix = ((this.prix * quantiteTotale) + (nouveauPrix * newQuantite))/(quantiteTotale + newQuantite);
	}

	public double getQuantiteTotale() {
		return quantiteTotale;
	}

	public void setQuantiteTotale(double quantiteTotale) {
		this.quantiteTotale = quantiteTotale;
	}
	
	public void addQuantite(double quantiteTotale) {
		this.quantiteTotale += quantiteTotale;
	}

	public Stock getStock() {
		return stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	
	public List<Demande> getDemandes() {
		return demandes;
	}

	public void setDemandes(List<Demande> demandes) {
		this.demandes = demandes;
	}

	public List<Catalogue> getCatalogues() {
		return catalogues;
	}

	public void setCatalogues(List<Catalogue> catalogues) {
		this.catalogues = catalogues;
	}

	public String getPrixFormate() {
		NumberFormat numberFormat = NumberFormat.getInstance(java.util.Locale.FRENCH);
		numberFormat.setMinimumFractionDigits(2);
		return numberFormat.format(prix);
	}

}

s2e_magasin_spring/WebContent/WEB-INF/jsp/footer.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<div class="row">
	<div class="wrap">
		<div class="col-sm-offset-1 col-sm-4">
			<div class="title">
				<h1>Testimoniala</h1>
			</div>
			<div class="content">
				<div class="testimonials">Accusantium dolo remque la udantium
					totam consequat tortor pretium sit amet volup</div>
			</div>
		</div>
		<div class="col-sm-offset-3 col-sm-3">
			<div class="title">
				<h1>Contact us</h1>
			</div>
			<div class="cotact">
				<ul>
					<li><img src="images/icon6.png" alt="" />(000) 888 888888</li>
					<li><img src="images/icon7.png" alt="" /><a href="#">info@companyname.com</a></li>
					<li><img src="images/icon8.png" alt="" />Name of site owner</li>
				</ul>
			</div>
		</div>
	</div>
</div>

s2e_magasin_spring/WebContent/WEB-INF/jsp/header.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ page import="static com.greta.s2e.magasin.globals.Constants.*"%>
<div class="header-wrap col-xs-12">
	<img class="col-xs-offset-2 col-xs-2"
		src="<%=RACINE%>/images/logo07-2.png" alt="" />
	<div class="col-xs-offset-3 col-xs-1">
		<h3>Magasin</h3>
	</div>
</div>

s2e_magasin_spring/WebContent/WEB-INF/jsp/liste_articles.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="static com.greta.s2e.magasin.globals.Constants.*"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>S2E - Magasin</title>
	<link href='<%= RACINE %>/bootstrap/css/bootstrap.css' rel='stylesheet' />
    <link href="<%= RACINE %>/css/styles.css" rel="stylesheet">
</head>
<body>
	<div class="container-fluid">
		<header class="row">
			<%@ include file="header.jsp"%>
		</header>
		
		<nav class="mainmenu">
			<div class="container">
				<%@ include file="menu.jsp"%>
			</div>
		</nav>
		
		<main class="container">
			<div class="row">
				<div class="box col-xs-offset-3 col-xs-4 text-center">
					<div class="panel">
						<div class="title">
							<h1>Liste des articles</h1>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th>Libelle</th>
							<th>Marque</th>
							<th>Modele</th>
							<th>Quantité</th>
							<th>Seuil minimum</th>
							<th>Seuil maximum</th>
							<th></th>
						</tr>
					</thead>
					<body>
						<c:forEach var="article" items="${listart}" varStatus="status">
							<tr>
								<td>${article.libelle}</td>
								<td>${article.marque}</td>
								<td>${article.modele}</td>
								<td>${article.stock.quantite}</td>
								<td>${article.stock.seuilMinimum}</td>
								<td>${article.stock.seuilMaximum}</td>
								<td><a class="btn" href="<%= PAGE_COMMANDES %>/new/${article.id}">Commande</a></td>
							</tr>
						</c:forEach>
					</body>
				</table>
			</div>
		</main>
		<footer class="container footer-wrap"> 
			<%@ include file="footer.jsp"%>
		</footer>
	</div>
</body>

</html>

s2e_magasin_spring/WebContent/WEB-INF/jsp/liste_commandes.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="static com.greta.s2e.magasin.globals.Constants.*"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>S2E - Magasin</title>
	<link href='<%= RACINE %>/bootstrap/css/bootstrap.css' rel='stylesheet' />
    <link href="<%= RACINE %>/css/styles.css" rel="stylesheet">
</head>
<body>
	<div class="container-fluid">
		<header class="row">
			<%@ include file="header.jsp"%>
		</header>
		
		<nav class="mainmenu">
			<div class="container">
				<%@ include file="menu.jsp"%>
			</div>
		</nav>
		
		<main class="container">
			<div class="row">
				<div class="box col-xs-offset-3 col-xs-4 text-center">
					<div class="panel">
						<div class="title">
							<h1>Liste des commandes</h1>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th>Date</th>
							<th>Article</th>
							<th>Quantite</th>
							<th>Fournisseur</th>
							<th>Montant</th>
							<th>Etat</th>
							<th></th>
						</tr>
					</thead>
					<body>
						<c:forEach var="commande" items="${liste}" varStatus="status">
							<tr>
								<td>${commande.date}</td>
								<td>${commande.articleCatalogue.article.marque} ${commande.articleCatalogue.article.modele} ${commande.articleCatalogue.article.libelle}</td>
								<td>${commande.quantite}</td>
								<td>${commande.articleCatalogue.fournisseur.nom}</td>
								<td>${commande.articleCatalogue.prix} €</td>
								<td>${commande.etat.libelle}</td>
								<td>
									<c:if test="${commande.etat.id == 'COUR'}">
										<a class="btn" href="<%= PAGE_COMMANDES %>/livrer/${ commande.id }">Livrée</a>
									</c:if>
								</td>
							</tr>
						</c:forEach>
					</body>
				</table>
			</div>
		
		</main>
		<footer class="container footer-wrap"> 
			<%@ include file="footer.jsp"%>
		</footer>
	</div>
</body>

</html>

s2e_magasin_spring/WebContent/WEB-INF/jsp/liste_demandes.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="static com.greta.s2e.magasin.globals.Constants.*"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>S2E - Magasin</title>
	<link href='<%= RACINE %>/bootstrap/css/bootstrap.css' rel='stylesheet' />
    <link href="<%= RACINE %>/css/styles.css" rel="stylesheet">
</head>
<body>
	<div class="container-fluid">
		<header class="row">
			<%@ include file="header.jsp"%>
		</header>
		
		<nav class="mainmenu">
			<div class="container">
				<%@ include file="menu.jsp"%>
			</div>
		</nav>
		
		<main class="container">
			<div class="row">
				<div class="box col-xs-offset-3 col-xs-4 text-center">
					<div class="panel">
						<div class="title">
							<h1>Liste des demandes</h1>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th>Date</th>
							<th>Etablissement</th>
							<th>Article</th>
							<th>Quantité commandée</th>
							<th>Quantité stock</th>
							<th>Etat</th>
							<th></th>
						</tr>
					</thead>
					<body>
						<c:forEach var="demande" items="${liste}" varStatus="status">
							<tr>
								<td><b>${demande.date}</b></td>
								<td>${demande.demandeur.etablissement.nom}</td>
								<td>${demande.article.libelle}</td>
								<td>${demande.quantite}</td>
								<td>${demande.article.stock.quantite}</td>
								<td>${demande.etat.libelle}</td>
								<td>
								<c:choose>
									<c:when test="${demande.etat.id == 'COUR'}">
										<a class="btn" href="<%= PAGE_DEMANDES %>/livrer/${ demande.id }">Livrée</a> 
										<a class="btn" href="<%= PAGE_DEMANDES %>/new/${ demande.id }/${ demande.article.id }">Commande</a>
									</c:when>
									<c:when test="${demande.etat.id == 'ATART'}">
										<a class="btn" href="<%= PAGE_DEMANDES %>/livrer/${ demande.id }">Livrer</a> 
									</c:when>
								</c:choose>
								</td>
							</tr>
						</c:forEach>
					</body>
				</table>
			</div>
		</main>
		<footer class="container footer-wrap"> 
			<%@ include file="footer.jsp"%>
		</footer>
	</div>
</body>

</html>

s2e_magasin_spring/WebContent/WEB-INF/jsp/menu.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ page import="static com.greta.s2e.magasin.globals.Constants.*"%>
<ul class="nav nav-pills col-sm-offset-0 col-sm-5">
	<li class="active"><a href="<%=RACINE%>/stock">Stock</a></li>
	<li><a href="<%=RACINE%>/demandes">Demandes</a></li>
	<li><a href="<%=RACINE%>/commandes">Commandes</a></li>
	<li><a href="<%= PAGE_DECONNEXION %>">Déconnexion</a></li>
</ul>
<ul class="nav nav-pills col-sm-offset-3 col-sm-4">
	<li><a class="social" href="#"><img
			src="<%=RACINE%>/images/aim.png" alt="" /></a></li>
	<li><a class="social" href="#"><img
			src="<%=RACINE%>/images/facebook.png" alt="" /></a></li>
	<li><a href="#"><img src="<%=RACINE%>/images/twwtter.png"
			alt="" /></a></li>
	<li><a href="#"><img src="<%=RACINE%>/images/linkedin.png"
			alt="" /></a></li>
</ul>

s2e_magasin_spring/WebContent/WEB-INF/jsp/new_commande.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="static com.greta.s2e.magasin.globals.Constants.*"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>  
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>S2E - Magasin</title>
	<link href="<c:url value="/bootstrap/css/bootstrap.css" />" rel='stylesheet' />
	<link href="<c:url value="/css/styles.css" />" rel="stylesheet">
</head>
<body>
	<div class="container-fluid">
		<header class="row">
			<%@ include file="header.jsp"%>
		</header>
		
		<nav class="mainmenu">
			<div class="container">
				<%@ include file="menu.jsp"%>
			</div>
		</nav>
		
		<main class="container">
			<div class="row">
				<form method="post" action="<%=PAGE_COMMANDES%>/enregistrer" 
					class="form form-horizontal col-xs-offset-2 col-xs-8">
					<fieldset>
					
						<!-- Form Name -->
						<legend>Nouvelle Commande</legend>
					
						<!-- Text output-->
						<div class="form-group">
							<label class="col-md-4 control-label" for="<%=PARAM_ARTICLE%>">Article</label>
							<div class="col-md-4">
								<c:out value="${article.libelle} ${article.marque} ${article.modele} - ${article.prixFormate} Euros"/>
							</div>
						</div>
						
						<!-- Select Basic -->
						<div class="form-group">
							<label class="col-md-4 control-label" for="<%= PARAM_CATALOGUE %>">Fournisseur</label>
							<div class="col-md-4">
								<select id="<%= PARAM_CATALOGUE %>" name="<%= PARAM_CATALOGUE %>"
										class="form-control">
									<option value="">- Choisissez un fournisseur -</option>
									<c:forEach items="${catalogues}" var="catalogue">
										<option value="${catalogue.id}">${catalogue.fournisseur.nom} - ${catalogue.prix} €</option>
									</c:forEach>
								</select>
							</div>
						</div>
						
						<!-- Text input-->
						<div class="form-group">
							<label class="col-md-4 control-label" for="<%=PARAM_QUANTITE%>">Quantité</label>
							<div class="col-md-4">
								<input id="<%=PARAM_QUANTITE%>" name="<%=PARAM_QUANTITE%>"
										class="form-control input-md" required=""
										type="text">
							</div>
						</div>
						
						<!-- Button -->
						<div class="form-group">
							<label class="col-md-4 control-label" for="valide"></label>
							<div class="col-md-4">
								<button id="valide" name="valide" class="btn">Valider</button>
							</div>
						</div>
						<c:if test="${ exception != null }">
							<div class="alert alert-danger">${ exception.exceptionMessage }</div>
						</c:if>
							
					</fieldset>
				</form>
			</div>
		</main>
		<footer class="container footer-wrap"> 
			<%@ include file="footer.jsp"%>
		</footer>
	</div>
</body>
</html>